# spring.main.web-application-type=none

# NOTE: You must disable the banner and the console logging 
# to allow the STDIO transport to work !!!
# spring.main.banner-mode=off
# logging.pattern.console=

#spring.ai.mcp.server.name=my-weather-server
#spring.ai.mcp.server.version=0.0.1
#
#spring.ai.mcp.server.protocol=STREAMABLE
#
#logging.file.name=./model-context-protocol/weather/starter-webflux-server/target/starter-webflux-server.log

# Server identification
spring.ai.mcp.server.name=my-weather-server
spring.ai.mcp.server.version=0.0.1

# Server type (SYNC/ASYNC)
spring.ai.mcp.server.type=SYNC

# Transport configuration
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.sse-message-endpoint=/mcp/message

# Change notifications
spring.ai.mcp.server.resource-change-notification=true
spring.ai.mcp.server.tool-change-notification=true
spring.ai.mcp.server.prompt-change-notification=true

# Logging (required for STDIO transport)
spring.main.banner-mode=off
#logging.file.name=./target/starter-webflux-server.log
logging.file.name=./model-context-protocol/weather/starter-webflux-server/target/starter-webflux-server.log